title: Appledore Documentation
theme: minima
remote_theme: pmarsceill/just-the-docs


title: Appledore Documentation
logo: "/assets/logo.png"
docs_dir: docs

extra_css:
  - "/assets/custom.css"

just_the_docs:
  show_breadcrumbs: true

just_the_docs:
  navigation:
    - title: "Getting Started"
      children:
        - title: "Installation"
          url: "/getting-started/installation"
    - title: "Features"
      children:
        - title: "Assertions"
          url: "/features/assertions"
        - title: "Binary System"
          url: "/features/binary_system"


plugins:
  - jekyll-toc

just_the_docs:
  navigation:
    - title: "Documentation"
      children:
        - title: "Assertions"
          url: "/assertions"
        - title: "Binary System"
          url: "/binary_system"
