title: Appledore Documentation
theme: minima
remote_theme: pages-themes/tactile

title: Appledore Documentation
logo: "/assets/logo.png"
docs_dir: docs

plugins:
  - jekyll-toc

just_the_docs:
  navigation:
    - title: "Documentation"
      children:
        - title: "Assertions"
          url: "/assertions"
        - title: "Binary System"
          url: "/binary_system"
